# Generated by Django 5.2.17 on 2026-10-04 00:20

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("digest", models.CharField(max_length=64)),
                ("created_lines", models.PositiveIntegerField(default=0)),
                ("skipped_lines", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_batches",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("store", "digest"), name="import_store_digest_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(max_length=64, verbose_name="Sipariş no"),
                ),
                (
                    "line_number",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Satır no",
                    ),
                ),
                ("order_date", models.DateField(verbose_name="Sipariş tarihi")),
                ("product_name", models.CharField(max_length=200, verbose_name="Ürün")),
                ("sku", models.CharField(max_length=64, verbose_name="Ürün kodu")),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Adet",
                    ),
                ),
                (
                    "unit_price_gross",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Birim fiyat (KDV dahil)",
                    ),
                ),
                (
                    "unit_cost_net",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Birim maliyet (KDV hariç)",
                    ),
                ),
                (
                    "vat_percent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="KDV (%)",
                    ),
                ),
                (
                    "commission_percent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Komisyon (%)",
                    ),
                ),
                (
                    "seller_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Satıcı indirimi (satır toplamı)",
                    ),
                ),
                (
                    "platform_coupon",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Pazaryeri kuponu (satır toplamı)",
                    ),
                ),
                (
                    "returned_quantity",
                    models.PositiveIntegerField(default=0, verbose_name="İade adedi"),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_lines",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-order_date", "order_number", "line_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("store", "order_number", "line_number"),
                        name="order_store_line_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gte", 1)),
                        name="order_quantity_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("line_number__gte", 1)),
                        name="order_line_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("returned_quantity__lte", models.F("quantity"))),
                        name="order_return_quantity_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("platform_coupon__gte", 0),
                            ("seller_discount__gte", 0),
                            ("unit_cost_net__gte", 0),
                            ("unit_price_gross__gte", 0),
                        ),
                        name="order_money_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("commission_percent__gte", 0),
                            ("commission_percent__lte", 100),
                            ("vat_percent__gte", 0),
                            ("vat_percent__lte", 100),
                        ),
                        name="order_rates_range",
                    ),
                ],
            },
        ),
    ]
