# Generated by Django 5.2.17 on 2026-10-04 01:57

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderline",
            name="cost_vat_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("20"),
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
                verbose_name="Maliyet KDV (%)",
            ),
        ),
        migrations.AddField(
            model_name="orderline",
            name="currency",
            field=models.CharField(
                choices=[("TRY", "TRY"), ("USD", "USD"), ("EUR", "EUR")],
                default="TRY",
                max_length=3,
                verbose_name="Para birimi",
            ),
        ),
        migrations.AddField(
            model_name="orderline",
            name="desi",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Birim desi",
            ),
        ),
        migrations.AddField(
            model_name="orderline",
            name="exchange_rate",
            field=models.DecimalField(
                decimal_places=6,
                default=Decimal("1"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.000001"))],
                verbose_name="Sipariş kuru (TRY)",
            ),
        ),
        migrations.AddField(
            model_name="orderline",
            name="weight_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Birim ağırlık (kg)",
            ),
        ),
        migrations.CreateModel(
            name="FinancialLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rule_version", models.CharField(default="demo-v1", max_length=30)),
                ("gross_sales", models.BigIntegerField()),
                ("net_sales", models.BigIntegerField()),
                ("commission", models.BigIntegerField()),
                ("shipping", models.BigIntegerField()),
                ("service", models.BigIntegerField()),
                ("cost", models.BigIntegerField()),
                ("withholding", models.BigIntegerField()),
                ("profit", models.BigIntegerField()),
                ("payout", models.BigIntegerField()),
                ("sales_vat", models.BigIntegerField()),
                ("fee_vat", models.BigIntegerField()),
                ("cost_vat", models.BigIntegerField()),
                (
                    "line",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial",
                        to="orders.orderline",
                    ),
                ),
            ],
        ),
    ]
