# Generated by Django 5.2.17 on 2026-10-04 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_orderline_cost_vat_percent_orderline_currency_and_more"),
        ("stores", "0002_alter_store_marketplace"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="orderline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("cost_vat_percent__gte", 0),
                    ("cost_vat_percent__lte", 100),
                    ("currency__in", ["TRY", "USD", "EUR"]),
                    ("desi__gte", 0),
                    ("exchange_rate__gt", 0),
                    ("weight_kg__gte", 0),
                ),
                name="order_shipping_fx_ranges",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("currency", "TRY"), _negated=True),
                    ("exchange_rate", 1),
                    _connector="OR",
                ),
                name="order_try_exchange_one",
            ),
        ),
    ]
