# Generated by Django 5.2.17 on 2026-10-04 18:53

import unicodedata

import django.db.models.deletion
from django.db import migrations, models


def backfill_import_and_search(apps, schema_editor):
    lines = apps.get_model("orders", "OrderLine")
    financials = apps.get_model("orders", "FinancialLine")
    alias = schema_editor.connection.alias
    for line in lines.objects.using(alias).iterator():
        search_text = unicodedata.normalize("NFC", f"{line.product_name}\n{line.sku}")
        search_text = search_text.translate(str.maketrans("İI", "iı")).lower()
        lines.objects.using(alias).filter(pk=line.pk).update(
            search_text=search_text,
        )
    financials.objects.using(alias).filter(line__store__marketplace="amazon_demo").update(
        rule_version="amazon-demo-v2"
    )


def restore_rule_label(apps, schema_editor):
    apps.get_model("orders", "FinancialLine").objects.using(schema_editor.connection.alias).filter(
        line__store__marketplace="amazon_demo", rule_version="amazon-demo-v2"
    ).update(rule_version="demo-v1")


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_orderline_order_shipping_fx_ranges_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderline",
            name="import_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="lines",
                to="orders.importbatch",
            ),
        ),
        migrations.AddField(
            model_name="orderline",
            name="imported_returned_quantity",
            field=models.PositiveIntegerField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="orderline",
            name="search_text",
            field=models.TextField(blank=True, default="", editable=False),
        ),
        migrations.RunPython(backfill_import_and_search, restore_rule_label),
    ]
