# Generated by Django 5.2.17 on 2026-10-04 00:20

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Mağaza adı")),
                (
                    "marketplace",
                    models.CharField(
                        choices=[("demo_tr", "Pazaryeri demo · TRY")],
                        default="demo_tr",
                        max_length=20,
                        verbose_name="Pazaryeri",
                    ),
                ),
                (
                    "commission_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Varsayılan komisyon (%)",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "name"), name="store_owner_name_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("commission_percent__gte", 0),
                            ("commission_percent__lte", 100),
                        ),
                        name="store_commission_range",
                    ),
                ],
            },
        ),
    ]
