# Generated by Django 5.2.17 on 2026-10-04 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="marketplace",
            field=models.CharField(
                choices=[
                    ("demo_tr", "Pazaryeri demo · TRY"),
                    ("amazon_demo", "Amazon demo · TRY / USD / EUR"),
                ],
                default="demo_tr",
                max_length=20,
                verbose_name="Pazaryeri",
            ),
        ),
    ]
